### ISSUE TITLE
Missing required options

### ISSUE THREAD

**Issue by dimovdaniel** [ulizama/TiFastlane#19]
Running tifast send

According to  http://docs.appcelerator.com/platform/latest/#!/guide/Appcelerator_CLI_Tasks-section-43306725_AppceleratorCLITasks-iTunesStore

`[ERROR] Missing required option: --distribution-name <name>
[ERROR] Missing required option: --pp-uuid <uuid>`

in index.js !line 555  you should add

buildArgs.push('-R');
                    buildArgs.push(cfg.team_name);
                     buildArgs.push('-P');
                    buildArgs.push(cfg.team_id);

Is there any other way I can contribute?

**Comment by DouglasHennrich** [comment]
I don't understand why you need to tell the distribution and provisioning through CLI... can you explain more? Thanks =)

**Comment by dimovdaniel** [comment]
I have the latest CLI, 5.0.4 and when I run the command bellow, no prompt is displayed, only the error. Same with when run from tifastline. 

```
dimovdaniel$ appc run -p ios -T dist-adhoc -O ./dist
Appcelerator Command-Line Interface, version 5.0.4
Copyright (c) 2014-2015, Appcelerator, Inc.  All Rights Reserved.

[ERROR] Missing required option: --distribution-name <name>

[ERROR] Missing required option: --pp-uuid <uuid>

For help, run: titanium help build

ERROR  | ti run exited with error code 1
```

**Comment by DouglasHennrich** [comment]
can you paste here your `tiapp.xml` ? I guess is something there

**Comment by dimovdaniel** [comment]
http://pastie.org/private/qxich5if1zrk6yrchxuddq

**Comment by DouglasHennrich** [comment]
If you're facing this problem when run `appc run -p ios -T dist-adhoc -O ./dist` so this must be an error on your `appc-cli`... run `appc ti setup` then select `check` and see if there's any error

**Comment by dimovdaniel** [comment]
Node.js
  ✓  node               installed (v0.10.13)
  ✓  npm                installed (v1.3.2)

Titanium CLI
  ✓  cli                up-to-date (v5.0.5)

Titanium CLI Dependencies
  ✓  async              up-to-date (v1.4.2)
  ✓  colors             up-to-date (v1.1.2)
  ✓  fields             up-to-date (v0.1.24)
  ✓  humanize           up-to-date (v0.0.9)
  ✓  longjohn           up-to-date (v0.2.9)
  ✓  moment             up-to-date (v2.10.6)
  ✓  node-appc          up-to-date (v0.2.31)
  ✓  request            up-to-date (v2.62.0)
  ✓  semver             up-to-date (v5.0.3)
  ✓  sprintf            up-to-date (v0.1.5)
  ✓  temp               up-to-date (v0.8.3)
  ✓  winston            up-to-date (v1.0.2)
  ✕  wrench             missing

Titanium SDK
  ✓  latest sdk         installed (v5.0.2.GA)
  ✓  selected sdk       up-to-date (v5.0.2.GA)

Mac OS X Environment
  ✓  CLI Tools          installed

iOS Environment
  ✓  Xcode              installed (7.1)
  ✓  iOS SDK            installed (9.1)
  ✓  WWDR cert          installed
  ✓  developer cert     installed (6 found)
  ✓  distribution cert  installed (12 found)
  ✓  dev provisioning   installed (28 found)
  ✓  dist provisioning  installed (71 found)

Android Environment
  ✓  sdk                installed (/Users/dimovdaniel/Documents/AndroidSDK)
  ✓  tools              installed (v24.3.4)
  ✓  platform tools     installed (v23.0.1)
  ✓  build tools        installed (v23.0.1)
  ✓  adb                installed /Users/dimovdaniel/Documents/AndroidSDK/platform-tools/adb
  ✓  android            installed /Users/dimovdaniel/Documents/AndroidSDK/tools/android
  ✓  emulator           installed /Users/dimovdaniel/Documents/AndroidSDK/tools/emulator
  ✓  mksdcard           installed /Users/dimovdaniel/Documents/AndroidSDK/tools/mksdcard
  ✓  zipalign           installed /Users/dimovdaniel/Documents/AndroidSDK/build-tools/23.0.1/zipalign
  ✓  aapt               installed /Users/dimovdaniel/Documents/AndroidSDK/build-tools/23.0.1/aapt
  ✓  aidl               installed /Users/dimovdaniel/Documents/AndroidSDK/build-tools/23.0.1/aidl
  ✓  targets            installed (20 found)
  ✓  avds               installed (6 found)
  !  ndk                Android NDK not found

Java Development Kit
  ✓  jdk                installed (v1.7.0)
  ✓  java               installed /Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/bin/java
  ✓  javac              installed /Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/bin/javac
  ✓  keytool            installed /Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/bin/keytool
  ✓  jarsigner          installed /Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/bin/jarsigner

Intel® Hardware Accelerated Execution Manager (HAXM)
  ✓  compatible  
  ✓  installed          

Network
  ✓  online             
-  no proxy server configured 
  ✓  Network connection test 
  ✓  Java-based connection test 

Directory Permissions
  ✓  home directory  
  ✓  titanium config directory 
  ✓  titanium sdk install directory 
  ✓  temp directory

**Comment by DouglasHennrich** [comment]
You have the right `certificate` installed ? Distribution certification

**Comment by dimovdaniel** [comment]
Yes, If I pass the distribution-name and pp-uuid as parameters  it works.

**Comment by DouglasHennrich** [comment]
this is really strange... is something with your `appc-cli` =l for me, it works fine... maybe you don't add the certificate on your keychain

**Comment by DouglasHennrich** [comment]
I guess I know what is wrong... type `appc ti setup` then go to `cli` and put **yes** for `Enable interactive prompting for missing options and arguments? (yes|no) [yes]:`

**Comment by dimovdaniel** [comment]
You save me a lot of time, manually searching for the Name, and for the uuid :+1:   Thanks a lot.

**Comment by DouglasHennrich** [comment]
:+1:  now you can use `tifast send` :D
