### ISSUE TITLE
Android [supply]: Use JSON credentials instead of P12

### ISSUE THREAD

**Issue by HazemKhaled** [ulizama/TiFastlane#25]
Supply still support P12 but will be deprecated soon

https://github.com/fastlane/fastlane/blob/fa5fc3ef7ef22c9e6b760f0e15b7f2498beb151e/supply/README.md#setup

**Comment by ulizama** [comment]
Thanks. It's on the list of changes that should happen as soon as I can.

**Comment by HazemKhaled** [comment]
OMG, my plan was to create my first pull request in TiFastlane today ... next great work @ulizama
