### ISSUE TITLE
tifastlane.cfg does not get created

### ISSUE THREAD

**Issue by DaveHudson** [ulizama/TiFastlane#26]
When running `tifast setup` the file `tifastlane.cfg` does not get created. 

Tried running as sudo and with 3 different versions of node using nvm but file never appears. 

Not a big deal as pretty easy to work out what structure of .cfg should be from https://github.com/ulizama/TiFastlane/blob/master/lib/templates.js but obviously might be a bit of blocker for some trying to get started with TiFastlane. 

Fantastic work btw! 👍

**Comment by ulizama** [comment]
I'm not able to reproduce, can you confirm your version?

`tifast -v`

**Comment by DaveHudson** [comment]
It's odd one! Some version info: 

oSX 10.11.4

```
tifast -v
0.6.0
```

```
node -v
v5.10.1
```

```
npm -v
3.8.3
```

**Comment by ulizama** [comment]
I wonder if is a permission issue in that specific app directory.

Can you try starting a new project and then running the `tifast setup` in that new one?

**Comment by DaveHudson** [comment]
I tried that but same result, so I dug a little deeper and established that dealWithResults() wasn't getting called. It appears the issue is with the inquirer npm module. 

Looking at the website https://www.npmjs.com/package/inquirer I noted it chained the function with a .then. A simple change from (pseudo code): 

```
inquirer.prompt([...], function ( answers ) {
      dealWithResults( answers );
}
```

to 

```
inquirer.prompt([ ... ]).then( function ( answers ) {
      dealWithResults( answers );
});
```

and it created the file perfectly! 

Inquirer does appear to have been recently so possibly we have different versions of the module installed and there was a breaking change?

FYI when I install TiFastlane I get version 1.0.2 of Inquirer

**Comment by jeffkempster** [comment]
I have the same issue. tifast setup works and asks me for info.  The last question is "Key Alias. Alias associated with your application's certificate."  After this the program ends and I never get a tifastlane.cfg file.  I have also tried this on a new project and also do not get tifastlane.cfg file. 

tifast -v 0.6.0
osx 10.11.4

thanks

**Comment by ulizama** [comment]
I think it is a problem with inquirer, can @jeffkempster and @DaveHudson confirm by reverting to an older version of inquirer:

`npm install inquirer@0.12.0`

And check if the issue persists?

Then I'll update our module to support the latest version.

**Comment by DaveHudson** [comment]
@ulizama I confirm if I install inquirer@0.12.0 then tifastlane.cfg does get created!
