### ISSUE TITLE
Distributing an iOS appstore build using dist-appstore

### ISSUE THREAD

**Issue by adri** [ulizama/TiFastlane#27]
Thank you for this project.

When calling `tifast send -t` or `tifast send` the build uses in both cases `-T dist-adhoc`. 
Is there a way to make an App Store build using `-T dist-appstore`? If not, is there a reason why only using `dist-adhoc`? We would need to load the right config depending on that value.

**Comment by ulizama** [comment]
To be able to automatically send the distribution through `fastlane` we need an .ipa to upload. If we use `dist-appstore` we get an archive and then the Archive Manager is launched, which doesn't allow for automatisation.

The only difference is the process that `titanium` uses, you DO need to make sure to select your AppStore Profile when prompted for which Profile to use.

**Comment by ulizama** [comment]
Umm, now that I think of it, you are talking about inside the app being able to detect if the build was `adhoc` or for `appstore`, right?

I wonder how we could go around that issue.
