### ISSUE TITLE
Add snapshot

### ISSUE THREAD

**Issue by thevirtualforge** [ulizama/TiFastlane#30]
Any plans to add Snapshot or technical reasons why it might not be possible?

_edit_ Just noticed that tifast DOES use Snapshot behind teh scenes. I meant stand alone snapshot functionality, ie. the ability to just grab app snapshots rather than as part of the `tifast send`

**Comment by ulizama** [comment]
`snapshot` needs to work with the Xcode Project directly and you need to follow a couple of steps on it to have it working, this is one of the reason why we haven't worked in integration directly with `tifast`
