### ISSUE TITLE
Usage queries

### ISSUE THREAD

**Issue by steveharman** [ulizama/TiFastlane#32]
Hi Uriel,

This is fantastic, great work!   I managed to get everything working ok but have some questions before we can get the most out of TiFastlane in our CI environment:

_1) How do we specify a provisioning profile to be used during the`ti send`phase?_
Currently I've been choosing one manually but that doesn't sit well with automation.

_2) How do we opt **not** to view the iTunes artwork / store listing preview?_
Again I've been accepting the`'Looks ok? y/n'` prompt manually.

_3) Is it a requirement to upload screenshots every time we `ti send`a binary to iTunes Connect?_
Our screenshots rarely change so it's an unnecessary step to send the iPhone & iPad screens every time.

_4 After the binary is uploaded to iTunes Connect how do we select it and choose 'Submit for Review' ?_
Again, I understand how to do this manually through the iTunes Connect portal - but can `ti send` be told to select the newly uploaded build & submit it for Apple's review?

Once again many thanks for TiFastlane.

Steve

**Comment by ulizama** [comment]
Hi Steve,

Everything that you need is possible. You can find the full list of options you can use on each action with `-h`, so for example: `tifast send -h`

Here are the specific options you would use to achieve what you need:
1. `tifast send --distribution_name [value] --pp_uuid [value]`
2. `tifast send --skip_verify`
3. `tifast send --skip_screenshots`
4. `tifast send --submit_for_review`

**Comment by steveharman** [comment]
Fantastic, thanks for the clarification.

Regards,

Steve
