### ISSUE TITLE
TestFlight XCode 8.3 compatibility

### ISSUE THREAD

**Issue by jvandijk** [ulizama/TiFastlane#42]
The 0.9.0 release works perfect for doing releases to the App Store, but the new logic for building the IPA should also be applied to the TestFlight option, because that also uses an IPA to push to TestFlight using Pilot.

**Comment by ulizama** [comment]
Missed that. I'll work on it as soon as I can.

**Comment by jvandijk** [comment]
Thanks @ulizama
